# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='标题')),
                ('content', models.TextField(null=True, verbose_name='内容')),
                ('keywords', models.CharField(max_length=50, null=True, unique=True, verbose_name='关键字')),
                ('describe', models.TextField(null=True, verbose_name='描述')),
                ('tags', models.CharField(max_length=100, unique=True, verbose_name='标签')),
                ('image', models.ImageField(null=True, upload_to='upload', verbose_name='标题图片')),
                ('publish_time', models.DateField(auto_now_add=True, verbose_name='发布日期')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('is_select', models.BooleanField(default=False, verbose_name='是否选择')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='栏目名称')),
                ('alias', models.CharField(max_length=100, unique=True, verbose_name='栏目别名')),
                ('father_node', models.CharField(max_length=100, null=True, verbose_name='父节点')),
                ('keyword', models.CharField(max_length=200, null=True, verbose_name='关键字')),
                ('description', models.TextField(null=True, verbose_name='描述')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField(verbose_name='摘要')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category'),
        ),
    ]
