# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo_brand',
            field=models.ImageField(null=True, upload_to='logo', verbose_name='品牌logo'),
        ),
    ]
