# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20190323_2118'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='newprice',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.AddField(
            model_name='orders',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='car.Carinfo', verbose_name='车辆'),
        ),
    ]
