# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('image_address', models.CharField(max_length=200, verbose_name='图像地址')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('target', models.IntegerField(choices=[(1, '_blank'), (2, '_self'), (3, '_top')], verbose_name='跳转页面的方式给')),
                ('rel', models.IntegerField(choices=[(1, 'nofollow'), (2, 'none')])),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'flink',
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_ip', models.CharField(max_length=20, verbose_name='登录者ip')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
            ],
            options={
                'db_table': 'login_record',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('keywords', models.CharField(max_length=200, verbose_name='关键字')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('announce_time', models.DateField(auto_now_add=True, verbose_name='公告发布日期')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('is_select', models.BooleanField(default=False, verbose_name='是否被选中')),
            ],
            options={
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truename', models.CharField(max_length=100, verbose_name='姓名')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=225, verbose_name='密码')),
                ('usertel', models.CharField(max_length=12, verbose_name='电话')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='announcer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='公告发布者'),
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='loginer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='flink',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='友情链接编辑者'),
        ),
    ]
