# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('username', models.CharField(max_length=24, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=225, verbose_name='密码')),
                ('tel', models.CharField(max_length=10, unique=True, verbose_name='电话')),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='标题')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='标签')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='栏目名称')),
                ('another_name', models.CharField(max_length=50, unique=True, verbose_name='栏目别名')),
                ('keyword', models.CharField(max_length=50, null=True, verbose_name='关键字')),
                ('describe', models.TextField(null=True, verbose_name='描述')),
            ],
            options={
                'db_table': 'classify',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField(verbose_name='摘要')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Article')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('login_ip', models.CharField(max_length=20, verbose_name='登录者ip')),
                ('loginer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Admin')),
            ],
            options={
                'db_table': 'login_record',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='标题')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='公告发布日期')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Admin')),
            ],
            options={
                'db_table': 'notice',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Classify'),
        ),
    ]
