# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Admin'),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='article',
            name='icon',
            field=models.ImageField(null=True, upload_to='upload', verbose_name='标题图片'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='tel',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='article',
            name='classify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Classify'),
        ),
    ]
