# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180925_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=1, verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='tel',
            field=models.CharField(max_length=11, null=True, verbose_name='电话'),
        ),
    ]
