# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180925_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='describe',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='label',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='icon',
            new_name='titlepic',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='关键字'),
        ),
    ]
