# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180925_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='classify',
            new_name='category',
        ),
    ]
