# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180925_0227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classify',
            new_name='Category',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
