# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('userpwd', models.CharField(max_length=255, verbose_name='密码')),
                ('realname', models.CharField(max_length=50, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('1', '男'), ('0', '女')], default='1', max_length=10, verbose_name='性别')),
                ('cellphone', models.CharField(max_length=11, verbose_name='手机')),
                ('uidentity', models.CharField(max_length=18, verbose_name='身份证')),
                ('address', models.CharField(max_length=150, verbose_name='地址')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
                'db_table': 'Users',
            },
        ),
    ]
